name: Makefile CI

on:
  push:
    branches: [ "mt5867_eu-user-11-RP1A.200720.011-1405406908-dev-keys" ]
  pull_request:
    branches: [ "mt5867_eu-user-11-RP1A.200720.011-1405406908-dev-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
